// Mocks generated by Mockito 5.4.6 from annotations
// in trip_tally/test/generate_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:io' as _i29;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter/foundation.dart' as _i10;
import 'package:flutter/material.dart' as _i9;
import 'package:flutter_bloc/flutter_bloc.dart' as _i24;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i26;
import 'package:permission_handler/permission_handler.dart' as _i39;
import 'package:shared_preferences/shared_preferences.dart' as _i8;
import 'package:trip_tally/data/api/api_client.dart' as _i25;
import 'package:trip_tally/data/api/osm_client.dart' as _i46;
import 'package:trip_tally/data/dto/expenses/create_expenses_dto.dart' as _i27;
import 'package:trip_tally/data/dto/expenses/expense_categories_dto.dart' as _i5;
import 'package:trip_tally/data/dto/expenses/expense_dto.dart' as _i50;
import 'package:trip_tally/data/dto/osm_map/osm_response_dto.dart' as _i11;
import 'package:trip_tally/data/dto/trips/create_trip_dto.dart' as _i28;
import 'package:trip_tally/data/dto/trips/get_trips_dto.dart' as _i6;
import 'package:trip_tally/data/dto/trips/trip_dto.dart' as _i7;
import 'package:trip_tally/data/dto/user/create_account_dto.dart' as _i20;
import 'package:trip_tally/data/dto/user/login_dto.dart' as _i19;
import 'package:trip_tally/data/dto/user/update_user_profile_dto.dart' as _i21;
import 'package:trip_tally/domain/data_source/authentication_remote_source.dart' as _i18;
import 'package:trip_tally/domain/data_source/expenses_remote_source.dart' as _i49;
import 'package:trip_tally/domain/data_source/osm_map_data_source.dart' as _i45;
import 'package:trip_tally/domain/data_source/trips_data_source.dart' as _i32;
import 'package:trip_tally/domain/entities/expenses/expense_categories_entity.dart' as _i54;
import 'package:trip_tally/domain/entities/expenses/expense_entity.dart' as _i52;
import 'package:trip_tally/domain/entities/osm_map/place_entity.dart' as _i42;
import 'package:trip_tally/domain/entities/trips/create_trip_entity.dart' as _i36;
import 'package:trip_tally/domain/entities/trips/trip_entity.dart' as _i35;
import 'package:trip_tally/domain/entities/user/create_account_entity.dart' as _i16;
import 'package:trip_tally/domain/entities/user/login_entity.dart' as _i15;
import 'package:trip_tally/domain/entities/user/update_user_profile_entity.dart' as _i17;
import 'package:trip_tally/domain/repositories/authentication_repo.dart' as _i12;
import 'package:trip_tally/domain/repositories/expenses_repo.dart' as _i53;
import 'package:trip_tally/domain/repositories/osm_map_repository.dart' as _i44;
import 'package:trip_tally/domain/repositories/trips_repo.dart' as _i34;
import 'package:trip_tally/domain/use_case/create_account_use_case.dart' as _i30;
import 'package:trip_tally/domain/use_case/create_expense_use_case.dart' as _i51;
import 'package:trip_tally/domain/use_case/create_trip_use_case.dart' as _i37;
import 'package:trip_tally/domain/use_case/delete_trip_use_case.dart' as _i62;
import 'package:trip_tally/domain/use_case/get_all_user_trips_use_case.dart' as _i60;
import 'package:trip_tally/domain/use_case/get_today_trips_use_case.dart' as _i66;
import 'package:trip_tally/domain/use_case/location_suggestions_use_case.dart' as _i41;
import 'package:trip_tally/domain/use_case/login_use_case.dart' as _i22;
import 'package:trip_tally/domain/use_case/sign_out_use_case.dart' as _i65;
import 'package:trip_tally/domain/use_case/update_trip_use_case.dart' as _i63;
import 'package:trip_tally/domain/use_case/update_user_profile_use_case.dart' as _i47;
import 'package:trip_tally/domain/utils/failure.dart' as _i14;
import 'package:trip_tally/domain/utils/shared_prefs_utils.dart' as _i31;
import 'package:trip_tally/domain/utils/success.dart' as _i3;
import 'package:trip_tally/presentation/pages/authentication_page/authentication_page.dart' as _i33;
import 'package:trip_tally/presentation/pages/authentication_page/bloc/authentication_bloc.dart' as _i23;
import 'package:trip_tally/presentation/pages/create_expenses_page/bloc/create_expenses_bloc.dart' as _i55;
import 'package:trip_tally/presentation/pages/create_expenses_page/bloc/create_expenses_event.dart' as _i56;
import 'package:trip_tally/presentation/pages/create_expenses_page/bloc/get_expense_categories_bloc.dart' as _i58;
import 'package:trip_tally/presentation/pages/create_trip_page/bloc/create_trip_bloc.dart' as _i57;
import 'package:trip_tally/presentation/pages/home_page/bloc/get_today_trips_bloc.dart' as _i67;
import 'package:trip_tally/presentation/pages/planned_trips_page/bloc/delete_trip_bloc.dart' as _i61;
import 'package:trip_tally/presentation/pages/planned_trips_page/bloc/get_all_user_trips_bloc.dart' as _i59;
import 'package:trip_tally/presentation/pages/planned_trips_page/bloc/update_trip_bloc.dart' as _i64;
import 'package:trip_tally/presentation/pages/welcome_page/bloc/update_user_profile_bloc.dart' as _i48;
import 'package:trip_tally/presentation/utils/basic_state.dart' as _i4;
import 'package:trip_tally/presentation/utils/permissions/bloc/permissions_bloc.dart' as _i40;
import 'package:trip_tally/presentation/utils/permissions/permission_service.dart' as _i38;
import 'package:trip_tally/presentation/widgets/m3_widgets/maps/osm_bloc/osm_suggestions_cubit.dart' as _i43;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSuccess_1 extends _i1.SmartFake implements _i3.Success {
  _FakeSuccess_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBasicState_2<T> extends _i1.SmartFake implements _i4.BasicState<T> {
  _FakeBasicState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExpenseCategoriesDto_3 extends _i1.SmartFake implements _i5.ExpenseCategoriesDto {
  _FakeExpenseCategoriesDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTripsDto_4 extends _i1.SmartFake implements _i6.GetTripsDto {
  _FakeGetTripsDto_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTripDto_5 extends _i1.SmartFake implements _i7.TripDto {
  _FakeTripDto_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_6 extends _i1.SmartFake implements _i8.SharedPreferences {
  _FakeSharedPreferences_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_7 extends _i1.SmartFake implements _i9.Widget {
  _FakeWidget_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i10.DiagnosticLevel? minLevel = _i10.DiagnosticLevel.info}) => super.toString();
}

class _FakeStatelessElement_8 extends _i1.SmartFake implements _i9.StatelessElement {
  _FakeStatelessElement_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i10.DiagnosticLevel? minLevel = _i10.DiagnosticLevel.info}) => super.toString();
}

class _FakeDiagnosticsNode_9 extends _i1.SmartFake implements _i10.DiagnosticsNode {
  _FakeDiagnosticsNode_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i10.TextTreeConfiguration? parentConfiguration,
    _i10.DiagnosticLevel? minLevel = _i10.DiagnosticLevel.info,
  }) =>
      super.toString();
}

class _FakeOsmResponseDto_10 extends _i1.SmartFake implements _i11.OsmResponseDto {
  _FakeOsmResponseDto_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthenticationRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepo extends _i1.Mock implements _i12.AuthenticationRepo {
  MockAuthenticationRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Success>> login(_i15.LoginEntity? entity) => (super.noSuchMethod(
        Invocation.method(
          #login,
          [entity],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>.value(_FakeEither_0<_i14.Failure, _i3.Success>(
          this,
          Invocation.method(
            #login,
            [entity],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Success>> createAccount(_i16.CreateAccountEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [entity],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>.value(_FakeEither_0<_i14.Failure, _i3.Success>(
          this,
          Invocation.method(
            #createAccount,
            [entity],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Success>> updateUserProfile(_i17.UpdateUserProfileEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [entity],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>.value(_FakeEither_0<_i14.Failure, _i3.Success>(
          this,
          Invocation.method(
            #updateUserProfile,
            [entity],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Success>> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>.value(_FakeEither_0<_i14.Failure, _i3.Success>(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>);
}

/// A class which mocks [AuthenticationRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRemoteSource extends _i1.Mock implements _i18.AuthenticationRemoteSource {
  MockAuthenticationRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i3.Success> login(_i19.LoginDto? loginDto) => (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginDto],
        ),
        returnValue: _i13.Future<_i3.Success>.value(_FakeSuccess_1(
          this,
          Invocation.method(
            #login,
            [loginDto],
          ),
        )),
      ) as _i13.Future<_i3.Success>);

  @override
  _i13.Future<_i3.Success> createAccount(_i20.CreateAccountDto? createUserDto) => (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [createUserDto],
        ),
        returnValue: _i13.Future<_i3.Success>.value(_FakeSuccess_1(
          this,
          Invocation.method(
            #createAccount,
            [createUserDto],
          ),
        )),
      ) as _i13.Future<_i3.Success>);

  @override
  _i13.Future<_i3.Success> updateUserProfile(_i21.UpdateUserProfileDto? dto) => (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [dto],
        ),
        returnValue: _i13.Future<_i3.Success>.value(_FakeSuccess_1(
          this,
          Invocation.method(
            #updateUserProfile,
            [dto],
          ),
        )),
      ) as _i13.Future<_i3.Success>);

  @override
  _i13.Future<_i3.Success> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i13.Future<_i3.Success>.value(_FakeSuccess_1(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i13.Future<_i3.Success>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i22.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Success>> call(_i15.LoginEntity? loginEntity) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [loginEntity],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>.value(_FakeEither_0<_i14.Failure, _i3.Success>(
          this,
          Invocation.method(
            #call,
            [loginEntity],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>);
}

/// A class which mocks [AuthenticationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationBloc extends _i1.Mock implements _i23.AuthenticationBloc {
  MockAuthenticationBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BasicState<void> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBasicState_2<void>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.BasicState<void>);

  @override
  _i13.Stream<_i4.BasicState<void>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i4.BasicState<void>>.empty(),
      ) as _i13.Stream<_i4.BasicState<void>>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i23.AuthenticationEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i23.AuthenticationEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.BasicState<void>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i23.AuthenticationEvent>(
    _i24.EventHandler<E, _i4.BasicState<void>>? handler, {
    _i24.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i24.Transition<_i23.AuthenticationEvent, _i4.BasicState<void>>? transition) => super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i24.Change<_i4.BasicState<void>>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i25.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i5.ExpenseCategoriesDto> getExpensesCategories() => (super.noSuchMethod(
        Invocation.method(
          #getExpensesCategories,
          [],
        ),
        returnValue: _i13.Future<_i5.ExpenseCategoriesDto>.value(_FakeExpenseCategoriesDto_3(
          this,
          Invocation.method(
            #getExpensesCategories,
            [],
          ),
        )),
      ) as _i13.Future<_i5.ExpenseCategoriesDto>);

  @override
  _i13.Future<_i6.GetTripsDto> getAllUserTrips() => (super.noSuchMethod(
        Invocation.method(
          #getAllUserTrips,
          [],
        ),
        returnValue: _i13.Future<_i6.GetTripsDto>.value(_FakeGetTripsDto_4(
          this,
          Invocation.method(
            #getAllUserTrips,
            [],
          ),
        )),
      ) as _i13.Future<_i6.GetTripsDto>);

  @override
  _i13.Future<_i7.TripDto> getTripById(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #getTripById,
          [tripId],
        ),
        returnValue: _i13.Future<_i7.TripDto>.value(_FakeTripDto_5(
          this,
          Invocation.method(
            #getTripById,
            [tripId],
          ),
        )),
      ) as _i13.Future<_i7.TripDto>);

  @override
  _i13.Future<_i7.TripDto> getTodayTrips() => (super.noSuchMethod(
        Invocation.method(
          #getTodayTrips,
          [],
        ),
        returnValue: _i13.Future<_i7.TripDto>.value(_FakeTripDto_5(
          this,
          Invocation.method(
            #getTodayTrips,
            [],
          ),
        )),
      ) as _i13.Future<_i7.TripDto>);

  @override
  _i13.Future<String> login(_i19.LoginDto? dto) => (super.noSuchMethod(
        Invocation.method(
          #login,
          [dto],
        ),
        returnValue: _i13.Future<String>.value(_i26.dummyValue<String>(
          this,
          Invocation.method(
            #login,
            [dto],
          ),
        )),
      ) as _i13.Future<String>);

  @override
  _i13.Future<String> createAccount(_i20.CreateAccountDto? dto) => (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [dto],
        ),
        returnValue: _i13.Future<String>.value(_i26.dummyValue<String>(
          this,
          Invocation.method(
            #createAccount,
            [dto],
          ),
        )),
      ) as _i13.Future<String>);

  @override
  _i13.Future<void> createExpenses(_i27.CreateExpensesDto? dto) => (super.noSuchMethod(
        Invocation.method(
          #createExpenses,
          [dto],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<_i7.TripDto> createTrip(_i28.CreateTripDto? dto) => (super.noSuchMethod(
        Invocation.method(
          #createTrip,
          [dto],
        ),
        returnValue: _i13.Future<_i7.TripDto>.value(_FakeTripDto_5(
          this,
          Invocation.method(
            #createTrip,
            [dto],
          ),
        )),
      ) as _i13.Future<_i7.TripDto>);

  @override
  _i13.Future<void> updateUserProfile({
    required String? username,
    required String? country,
    required String? defaultCurrencyCode,
    _i29.File? profilePicture,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {
            #username: username,
            #country: country,
            #defaultCurrencyCode: defaultCurrencyCode,
            #profilePicture: profilePicture,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> updateTrip(
    String? tripId,
    _i28.CreateTripDto? dto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTrip,
          [
            tripId,
            dto,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> deleteTrip(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTrip,
          [tripId],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i8.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) => (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i13.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [CreateAccountUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateAccountUseCase extends _i1.Mock implements _i30.CreateAccountUseCase {
  MockCreateAccountUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Success>> call(_i16.CreateAccountEntity? entity) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [entity],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>.value(_FakeEither_0<_i14.Failure, _i3.Success>(
          this,
          Invocation.method(
            #call,
            [entity],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>);
}

/// A class which mocks [SharedPrefsUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPrefsUtils extends _i1.Mock implements _i31.SharedPrefsUtils {
  MockSharedPrefsUtils() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.SharedPreferences get prefs => (super.noSuchMethod(
        Invocation.getter(#prefs),
        returnValue: _FakeSharedPreferences_6(
          this,
          Invocation.getter(#prefs),
        ),
      ) as _i8.SharedPreferences);

  @override
  _i13.Future<bool> get removeToken => (super.noSuchMethod(
        Invocation.getter(#removeToken),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<void> saveToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [token],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [TripsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTripsDataSource extends _i1.Mock implements _i32.TripsDataSource {
  MockTripsDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i7.TripDto> createTrip(_i28.CreateTripDto? dto) => (super.noSuchMethod(
        Invocation.method(
          #createTrip,
          [dto],
        ),
        returnValue: _i13.Future<_i7.TripDto>.value(_FakeTripDto_5(
          this,
          Invocation.method(
            #createTrip,
            [dto],
          ),
        )),
      ) as _i13.Future<_i7.TripDto>);

  @override
  _i13.Future<List<_i7.TripDto>> getAllUserTrips() => (super.noSuchMethod(
        Invocation.method(
          #getAllUserTrips,
          [],
        ),
        returnValue: _i13.Future<List<_i7.TripDto>>.value(<_i7.TripDto>[]),
      ) as _i13.Future<List<_i7.TripDto>>);

  @override
  _i13.Future<_i7.TripDto?> getTodayTrips() => (super.noSuchMethod(
        Invocation.method(
          #getTodayTrips,
          [],
        ),
        returnValue: _i13.Future<_i7.TripDto?>.value(),
      ) as _i13.Future<_i7.TripDto?>);

  @override
  _i13.Future<_i7.TripDto> getTripById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTripById,
          [id],
        ),
        returnValue: _i13.Future<_i7.TripDto>.value(_FakeTripDto_5(
          this,
          Invocation.method(
            #getTripById,
            [id],
          ),
        )),
      ) as _i13.Future<_i7.TripDto>);

  @override
  _i13.Future<_i3.Success> deleteTrip(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTrip,
          [id],
        ),
        returnValue: _i13.Future<_i3.Success>.value(_FakeSuccess_1(
          this,
          Invocation.method(
            #deleteTrip,
            [id],
          ),
        )),
      ) as _i13.Future<_i3.Success>);

  @override
  _i13.Future<_i3.Success> updateTrip(
    String? id,
    _i28.CreateTripDto? dto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTrip,
          [
            id,
            dto,
          ],
        ),
        returnValue: _i13.Future<_i3.Success>.value(_FakeSuccess_1(
          this,
          Invocation.method(
            #updateTrip,
            [
              id,
              dto,
            ],
          ),
        )),
      ) as _i13.Future<_i3.Success>);
}

/// A class which mocks [AuthenticationPage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationPage extends _i1.Mock implements _i33.AuthenticationPage {
  MockAuthenticationPage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Widget build(_i9.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #build,
          [context],
        ),
        returnValue: _FakeWidget_7(
          this,
          Invocation.method(
            #build,
            [context],
          ),
        ),
      ) as _i9.Widget);

  @override
  _i9.StatelessElement createElement() => (super.noSuchMethod(
        Invocation.method(
          #createElement,
          [],
        ),
        returnValue: _FakeStatelessElement_8(
          this,
          Invocation.method(
            #createElement,
            [],
          ),
        ),
      ) as _i9.StatelessElement);

  @override
  String toStringShort() => (super.noSuchMethod(
        Invocation.method(
          #toStringShort,
          [],
        ),
        returnValue: _i26.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShort,
            [],
          ),
        ),
      ) as String);

  @override
  void debugFillProperties(_i10.DiagnosticPropertiesBuilder? properties) => super.noSuchMethod(
        Invocation.method(
          #debugFillProperties,
          [properties],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String toStringShallow({
    String? joiner = ', ',
    _i10.DiagnosticLevel? minLevel = _i10.DiagnosticLevel.debug,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStringShallow,
          [],
          {
            #joiner: joiner,
            #minLevel: minLevel,
          },
        ),
        returnValue: _i26.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShallow,
            [],
            {
              #joiner: joiner,
              #minLevel: minLevel,
            },
          ),
        ),
      ) as String);

  @override
  String toStringDeep({
    String? prefixLineOne = '',
    String? prefixOtherLines,
    _i10.DiagnosticLevel? minLevel = _i10.DiagnosticLevel.debug,
    int? wrapWidth = 65,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStringDeep,
          [],
          {
            #prefixLineOne: prefixLineOne,
            #prefixOtherLines: prefixOtherLines,
            #minLevel: minLevel,
            #wrapWidth: wrapWidth,
          },
        ),
        returnValue: _i26.dummyValue<String>(
          this,
          Invocation.method(
            #toStringDeep,
            [],
            {
              #prefixLineOne: prefixLineOne,
              #prefixOtherLines: prefixOtherLines,
              #minLevel: minLevel,
              #wrapWidth: wrapWidth,
            },
          ),
        ),
      ) as String);

  @override
  _i10.DiagnosticsNode toDiagnosticsNode({
    String? name,
    _i10.DiagnosticsTreeStyle? style,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toDiagnosticsNode,
          [],
          {
            #name: name,
            #style: style,
          },
        ),
        returnValue: _FakeDiagnosticsNode_9(
          this,
          Invocation.method(
            #toDiagnosticsNode,
            [],
            {
              #name: name,
              #style: style,
            },
          ),
        ),
      ) as _i10.DiagnosticsNode);

  @override
  List<_i10.DiagnosticsNode> debugDescribeChildren() => (super.noSuchMethod(
        Invocation.method(
          #debugDescribeChildren,
          [],
        ),
        returnValue: <_i10.DiagnosticsNode>[],
      ) as List<_i10.DiagnosticsNode>);

  @override
  String toString({_i10.DiagnosticLevel? minLevel = _i10.DiagnosticLevel.info}) => super.toString();
}

/// A class which mocks [TripsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockTripsRepo extends _i1.Mock implements _i34.TripsRepo {
  MockTripsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity>> createTrip(_i36.CreateTripEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTrip,
          [entity],
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity>>.value(_FakeEither_0<_i14.Failure, _i35.TripEntity>(
          this,
          Invocation.method(
            #createTrip,
            [entity],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, List<_i35.TripEntity>>> getAllUserTrips() => (super.noSuchMethod(
        Invocation.method(
          #getAllUserTrips,
          [],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, List<_i35.TripEntity>>>.value(
            _FakeEither_0<_i14.Failure, List<_i35.TripEntity>>(
          this,
          Invocation.method(
            #getAllUserTrips,
            [],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, List<_i35.TripEntity>>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity?>> getTodayTrips() => (super.noSuchMethod(
        Invocation.method(
          #getTodayTrips,
          [],
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity?>>.value(_FakeEither_0<_i14.Failure, _i35.TripEntity?>(
          this,
          Invocation.method(
            #getTodayTrips,
            [],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity?>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity>> getTripById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTripById,
          [id],
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity>>.value(_FakeEither_0<_i14.Failure, _i35.TripEntity>(
          this,
          Invocation.method(
            #getTripById,
            [id],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Success>> deleteTrip(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTrip,
          [id],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>.value(_FakeEither_0<_i14.Failure, _i3.Success>(
          this,
          Invocation.method(
            #deleteTrip,
            [id],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Success>> updateTrip(
    String? id,
    _i36.CreateTripEntity? entity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTrip,
          [
            id,
            entity,
          ],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>.value(_FakeEither_0<_i14.Failure, _i3.Success>(
          this,
          Invocation.method(
            #updateTrip,
            [
              id,
              entity,
            ],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>);
}

/// A class which mocks [CreateTripUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateTripUseCase extends _i1.Mock implements _i37.CreateTripUseCase {
  MockCreateTripUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity>> call(_i36.CreateTripEntity? entity) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [entity],
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity>>.value(_FakeEither_0<_i14.Failure, _i35.TripEntity>(
          this,
          Invocation.method(
            #call,
            [entity],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity>>);
}

/// A class which mocks [PermissionsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionsService extends _i1.Mock implements _i38.PermissionsService {
  MockPermissionsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i39.PermissionStatus> status(_i39.Permission? permission) => (super.noSuchMethod(
        Invocation.method(
          #status,
          [permission],
        ),
        returnValue: _i13.Future<_i39.PermissionStatus>.value(_i39.PermissionStatus.denied),
      ) as _i13.Future<_i39.PermissionStatus>);

  @override
  _i13.Future<bool> openAppSettings() => (super.noSuchMethod(
        Invocation.method(
          #openAppSettings,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<_i39.PermissionStatus> request(_i39.Permission? permission) => (super.noSuchMethod(
        Invocation.method(
          #request,
          [permission],
        ),
        returnValue: _i13.Future<_i39.PermissionStatus>.value(_i39.PermissionStatus.denied),
      ) as _i13.Future<_i39.PermissionStatus>);
}

/// A class which mocks [PermissionsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionsBloc extends _i1.Mock implements _i40.PermissionsBloc {
  MockPermissionsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BasicState<_i39.PermissionStatus> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBasicState_2<_i39.PermissionStatus>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.BasicState<_i39.PermissionStatus>);

  @override
  _i13.Stream<_i4.BasicState<_i39.PermissionStatus>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i4.BasicState<_i39.PermissionStatus>>.empty(),
      ) as _i13.Stream<_i4.BasicState<_i39.PermissionStatus>>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i40.PermissionsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i40.PermissionsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.BasicState<_i39.PermissionStatus>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i40.PermissionsEvent>(
    _i24.EventHandler<E, _i4.BasicState<_i39.PermissionStatus>>? handler, {
    _i24.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i24.Transition<_i40.PermissionsEvent, _i4.BasicState<_i39.PermissionStatus>>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i24.Change<_i4.BasicState<_i39.PermissionStatus>>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocationSuggestionsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationSuggestionsUseCase extends _i1.Mock implements _i41.LocationSuggestionsUseCase {
  MockLocationSuggestionsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, List<_i42.PlaceEntity>>> call(String? input) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [input],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, List<_i42.PlaceEntity>>>.value(
            _FakeEither_0<_i14.Failure, List<_i42.PlaceEntity>>(
          this,
          Invocation.method(
            #call,
            [input],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, List<_i42.PlaceEntity>>>);
}

/// A class which mocks [OsmSuggestionsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockOsmSuggestionsCubit extends _i1.Mock implements _i43.OsmSuggestionsCubit {
  MockOsmSuggestionsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BasicState<List<_i42.PlaceEntity>> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBasicState_2<List<_i42.PlaceEntity>>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.BasicState<List<_i42.PlaceEntity>>);

  @override
  _i13.Stream<_i4.BasicState<List<_i42.PlaceEntity>>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i4.BasicState<List<_i42.PlaceEntity>>>.empty(),
      ) as _i13.Stream<_i4.BasicState<List<_i42.PlaceEntity>>>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<List<_i42.PlaceEntity>> getSuggestions(String? query) => (super.noSuchMethod(
        Invocation.method(
          #getSuggestions,
          [query],
        ),
        returnValue: _i13.Future<List<_i42.PlaceEntity>>.value(<_i42.PlaceEntity>[]),
      ) as _i13.Future<List<_i42.PlaceEntity>>);

  @override
  void emit(_i4.BasicState<List<_i42.PlaceEntity>>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i24.Change<_i4.BasicState<List<_i42.PlaceEntity>>>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [OsmMapRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOsmMapRepository extends _i1.Mock implements _i44.OsmMapRepository {
  MockOsmMapRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, List<_i42.PlaceEntity>>> getPlaces(String? input) => (super.noSuchMethod(
        Invocation.method(
          #getPlaces,
          [input],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, List<_i42.PlaceEntity>>>.value(
            _FakeEither_0<_i14.Failure, List<_i42.PlaceEntity>>(
          this,
          Invocation.method(
            #getPlaces,
            [input],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, List<_i42.PlaceEntity>>>);
}

/// A class which mocks [OsmMapDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOsmMapDataSource extends _i1.Mock implements _i45.OsmMapDataSource {
  MockOsmMapDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i11.FeatureDto>> getPlaces(String? input) => (super.noSuchMethod(
        Invocation.method(
          #getPlaces,
          [input],
        ),
        returnValue: _i13.Future<List<_i11.FeatureDto>>.value(<_i11.FeatureDto>[]),
      ) as _i13.Future<List<_i11.FeatureDto>>);
}

/// A class which mocks [OsmClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockOsmClient extends _i1.Mock implements _i46.OsmClient {
  MockOsmClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i11.OsmResponseDto> getLocationSuggestions({
    required String? input,
    String? format = 'geojson',
    int? addressDetails = 1,
    int? limit = 5,
    String? acceptLanguage = 'en',
    int? polygonSvg = 1,
    int? extraTags = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationSuggestions,
          [],
          {
            #input: input,
            #format: format,
            #addressDetails: addressDetails,
            #limit: limit,
            #acceptLanguage: acceptLanguage,
            #polygonSvg: polygonSvg,
            #extraTags: extraTags,
          },
        ),
        returnValue: _i13.Future<_i11.OsmResponseDto>.value(_FakeOsmResponseDto_10(
          this,
          Invocation.method(
            #getLocationSuggestions,
            [],
            {
              #input: input,
              #format: format,
              #addressDetails: addressDetails,
              #limit: limit,
              #acceptLanguage: acceptLanguage,
              #polygonSvg: polygonSvg,
              #extraTags: extraTags,
            },
          ),
        )),
      ) as _i13.Future<_i11.OsmResponseDto>);
}

/// A class which mocks [UpdateUserProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserProfileUseCase extends _i1.Mock implements _i47.UpdateUserProfileUseCase {
  MockUpdateUserProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Success>> call(_i17.UpdateUserProfileEntity? entity) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [entity],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>.value(_FakeEither_0<_i14.Failure, _i3.Success>(
          this,
          Invocation.method(
            #call,
            [entity],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>);
}

/// A class which mocks [UpdateUserProfileBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserProfileBloc extends _i1.Mock implements _i48.UpdateUserProfileBloc {
  MockUpdateUserProfileBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BasicState<void> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBasicState_2<void>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.BasicState<void>);

  @override
  _i13.Stream<_i4.BasicState<void>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i4.BasicState<void>>.empty(),
      ) as _i13.Stream<_i4.BasicState<void>>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i48.UpdateUserProfileEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i48.UpdateUserProfileEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.BasicState<void>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i48.UpdateUserProfileEvent>(
    _i24.EventHandler<E, _i4.BasicState<void>>? handler, {
    _i24.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i24.Transition<_i48.UpdateUserProfileEvent, _i4.BasicState<void>>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i24.Change<_i4.BasicState<void>>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ExpensesRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpensesRemoteSource extends _i1.Mock implements _i49.ExpensesRemoteSource {
  MockExpensesRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i3.Success> createExpenses(List<_i50.ExpenseDto>? dto) => (super.noSuchMethod(
        Invocation.method(
          #createExpenses,
          [dto],
        ),
        returnValue: _i13.Future<_i3.Success>.value(_FakeSuccess_1(
          this,
          Invocation.method(
            #createExpenses,
            [dto],
          ),
        )),
      ) as _i13.Future<_i3.Success>);

  @override
  _i13.Future<_i5.ExpenseCategoriesDto> getExpenseCategories() => (super.noSuchMethod(
        Invocation.method(
          #getExpenseCategories,
          [],
        ),
        returnValue: _i13.Future<_i5.ExpenseCategoriesDto>.value(_FakeExpenseCategoriesDto_3(
          this,
          Invocation.method(
            #getExpenseCategories,
            [],
          ),
        )),
      ) as _i13.Future<_i5.ExpenseCategoriesDto>);
}

/// A class which mocks [CreateExpensesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateExpensesUseCase extends _i1.Mock implements _i51.CreateExpensesUseCase {
  MockCreateExpensesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Success>> call(List<_i52.ExpenseEntity>? entities) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [entities],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>.value(_FakeEither_0<_i14.Failure, _i3.Success>(
          this,
          Invocation.method(
            #call,
            [entities],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>);
}

/// A class which mocks [ExpensesRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpensesRepo extends _i1.Mock implements _i53.ExpensesRepo {
  MockExpensesRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Success>> createExpenses(List<_i52.ExpenseEntity>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExpenses,
          [entities],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>.value(_FakeEither_0<_i14.Failure, _i3.Success>(
          this,
          Invocation.method(
            #createExpenses,
            [entities],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i54.ExpenseCategoriesEntity>> getExpenseCategories() => (super.noSuchMethod(
        Invocation.method(
          #getExpenseCategories,
          [],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i54.ExpenseCategoriesEntity>>.value(
            _FakeEither_0<_i14.Failure, _i54.ExpenseCategoriesEntity>(
          this,
          Invocation.method(
            #getExpenseCategories,
            [],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i54.ExpenseCategoriesEntity>>);
}

/// A class which mocks [CreateExpensesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateExpensesBloc extends _i1.Mock implements _i55.CreateExpensesBloc {
  MockCreateExpensesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BasicState<void> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBasicState_2<void>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.BasicState<void>);

  @override
  _i13.Stream<_i4.BasicState<void>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i4.BasicState<void>>.empty(),
      ) as _i13.Stream<_i4.BasicState<void>>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i56.CreateExpensesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i56.CreateExpensesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.BasicState<void>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i56.CreateExpensesEvent>(
    _i24.EventHandler<E, _i4.BasicState<void>>? handler, {
    _i24.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i24.Transition<_i56.CreateExpensesEvent, _i4.BasicState<void>>? transition) => super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i24.Change<_i4.BasicState<void>>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CreateTripBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateTripBloc extends _i1.Mock implements _i57.CreateTripBloc {
  MockCreateTripBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BasicState<_i35.TripEntity> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBasicState_2<_i35.TripEntity>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.BasicState<_i35.TripEntity>);

  @override
  _i13.Stream<_i4.BasicState<_i35.TripEntity>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i4.BasicState<_i35.TripEntity>>.empty(),
      ) as _i13.Stream<_i4.BasicState<_i35.TripEntity>>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i57.CreateTripEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i57.CreateTripEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.BasicState<_i35.TripEntity>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i57.CreateTripEvent>(
    _i24.EventHandler<E, _i4.BasicState<_i35.TripEntity>>? handler, {
    _i24.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i24.Transition<_i57.CreateTripEvent, _i4.BasicState<_i35.TripEntity>>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i24.Change<_i4.BasicState<_i35.TripEntity>>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GetExpenseCategoriesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExpenseCategoriesBloc extends _i1.Mock implements _i58.GetExpenseCategoriesBloc {
  MockGetExpenseCategoriesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BasicState<_i54.ExpenseCategoriesEntity> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBasicState_2<_i54.ExpenseCategoriesEntity>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.BasicState<_i54.ExpenseCategoriesEntity>);

  @override
  _i13.Stream<_i4.BasicState<_i54.ExpenseCategoriesEntity>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i4.BasicState<_i54.ExpenseCategoriesEntity>>.empty(),
      ) as _i13.Stream<_i4.BasicState<_i54.ExpenseCategoriesEntity>>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i58.GetExpenseCategoriesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i58.GetExpenseCategoriesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.BasicState<_i54.ExpenseCategoriesEntity>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i58.GetExpenseCategoriesEvent>(
    _i24.EventHandler<E, _i4.BasicState<_i54.ExpenseCategoriesEntity>>? handler, {
    _i24.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i24.Transition<_i58.GetExpenseCategoriesEvent, _i4.BasicState<_i54.ExpenseCategoriesEntity>>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i24.Change<_i4.BasicState<_i54.ExpenseCategoriesEntity>>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GetAllUserTripsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllUserTripsBloc extends _i1.Mock implements _i59.GetAllUserTripsBloc {
  MockGetAllUserTripsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BasicState<List<_i35.TripEntity>> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBasicState_2<List<_i35.TripEntity>>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.BasicState<List<_i35.TripEntity>>);

  @override
  _i13.Stream<_i4.BasicState<List<_i35.TripEntity>>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i4.BasicState<List<_i35.TripEntity>>>.empty(),
      ) as _i13.Stream<_i4.BasicState<List<_i35.TripEntity>>>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i59.GetAllUserTripsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i59.GetAllUserTripsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.BasicState<List<_i35.TripEntity>>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i59.GetAllUserTripsEvent>(
    _i24.EventHandler<E, _i4.BasicState<List<_i35.TripEntity>>>? handler, {
    _i24.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i24.Transition<_i59.GetAllUserTripsEvent, _i4.BasicState<List<_i35.TripEntity>>>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i24.Change<_i4.BasicState<List<_i35.TripEntity>>>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GetAllUserTripsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllUserTripsUseCase extends _i1.Mock implements _i60.GetAllUserTripsUseCase {
  MockGetAllUserTripsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, List<_i35.TripEntity>>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, List<_i35.TripEntity>>>.value(
            _FakeEither_0<_i14.Failure, List<_i35.TripEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, List<_i35.TripEntity>>>);
}

/// A class which mocks [DeleteTripBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteTripBloc extends _i1.Mock implements _i61.DeleteTripBloc {
  MockDeleteTripBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BasicState<void> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBasicState_2<void>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.BasicState<void>);

  @override
  _i13.Stream<_i4.BasicState<void>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i4.BasicState<void>>.empty(),
      ) as _i13.Stream<_i4.BasicState<void>>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i61.DeleteTripEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i61.DeleteTripEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.BasicState<void>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i61.DeleteTripEvent>(
    _i24.EventHandler<E, _i4.BasicState<void>>? handler, {
    _i24.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i24.Transition<_i61.DeleteTripEvent, _i4.BasicState<void>>? transition) => super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i24.Change<_i4.BasicState<void>>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DeleteTripUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteTripUseCase extends _i1.Mock implements _i62.DeleteTripUseCase {
  MockDeleteTripUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Success>> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>.value(_FakeEither_0<_i14.Failure, _i3.Success>(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>);
}

/// A class which mocks [UpdateTripUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateTripUseCase extends _i1.Mock implements _i63.UpdateTripUseCase {
  MockUpdateTripUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Success>> call(_i63.UpdateTripUseCaseParams? params) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>.value(_FakeEither_0<_i14.Failure, _i3.Success>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>);
}

/// A class which mocks [UpdateTripBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateTripBloc extends _i1.Mock implements _i64.UpdateTripBloc {
  MockUpdateTripBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BasicState<void> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBasicState_2<void>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.BasicState<void>);

  @override
  _i13.Stream<_i4.BasicState<void>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i4.BasicState<void>>.empty(),
      ) as _i13.Stream<_i4.BasicState<void>>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i64.UpdateTripEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i64.UpdateTripEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.BasicState<void>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i64.UpdateTripEvent>(
    _i24.EventHandler<E, _i4.BasicState<void>>? handler, {
    _i24.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i24.Transition<_i64.UpdateTripEvent, _i4.BasicState<void>>? transition) => super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i24.Change<_i4.BasicState<void>>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SignOutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutUseCase extends _i1.Mock implements _i65.SignOutUseCase {
  MockSignOutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Success>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>.value(_FakeEither_0<_i14.Failure, _i3.Success>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Success>>);
}

/// A class which mocks [GetTodayTripsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTodayTripsUseCase extends _i1.Mock implements _i66.GetTodayTripsUseCase {
  MockGetTodayTripsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity?>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity?>>.value(_FakeEither_0<_i14.Failure, _i35.TripEntity?>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i35.TripEntity?>>);
}

/// A class which mocks [GetTodayTripsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTodayTripsBloc extends _i1.Mock implements _i67.GetTodayTripsBloc {
  MockGetTodayTripsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BasicState<_i35.TripEntity?> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBasicState_2<_i35.TripEntity?>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.BasicState<_i35.TripEntity?>);

  @override
  _i13.Stream<_i4.BasicState<_i35.TripEntity?>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i4.BasicState<_i35.TripEntity?>>.empty(),
      ) as _i13.Stream<_i4.BasicState<_i35.TripEntity?>>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i67.GetTodayTripsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i67.GetTodayTripsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.BasicState<_i35.TripEntity?>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i67.GetTodayTripsEvent>(
    _i24.EventHandler<E, _i4.BasicState<_i35.TripEntity?>>? handler, {
    _i24.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i24.Transition<_i67.GetTodayTripsEvent, _i4.BasicState<_i35.TripEntity?>>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i24.Change<_i4.BasicState<_i35.TripEntity?>>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
