name: trip_tally
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.29.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  # auto_route
  auto_route: ^10.0.1

  # immutable_classes
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0

  # serialization
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # http client
  dio: ^5.4.0
  retrofit: ^4.0.3

  #logger
  pretty_dio_logger: ^1.3.1

  # dependency injection
  get_it: ^8.0.3
  injectable: ^2.3.2

  # internationalization and localization
  intl: ^0.20.2
  intl_utils: ^2.8.7
  flutter_localizations:
    sdk: flutter

  # ui
  flutter_svg: ^2.0.9

  # functional programming
  dartz: ^0.10.1

  # business logic
  flutter_bloc: ^9.1.0

  # testing
  mockito: ^5.4.4
  bloc_test: ^10.0.0
  equatable: ^2.0.5
  golden_toolkit: ^0.15.0
  alchemist: ^0.11.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  file: ^7.0.0
  country_flags: ^4.0.0
  shared_preferences: ^2.2.3
  auto_size_text: ^3.0.0
  flutter_animate: ^4.5.0
  currency_picker: ^2.0.21
  country_picker: ^2.0.26
  world_countries: ^3.4.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  flutter_typeahead: ^5.2.0
  table_calendar: ^3.1.2
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  flutter_map_location_marker: ^10.0.0
  flutter_map_cancellable_tile_provider: ^3.0.0
  material_floating_search_bar_2: ^0.5.0
  geolocator: ^14.0.2
  path: ^1.9.0
  dropdown_search: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  retrofit_generator: ^9.1.9
  injectable_generator: ^2.4.1
  build_runner: ^2.4.9
  analyzer: ^7.3.0
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/presentation/assets/svg/
    - lib/presentation/assets/m3_svg/
    - lib/presentation/assets/png/

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/presentation/assets/m3_fonts/roboto/Roboto-Thin.ttf
          weight: 200
        - asset: lib/presentation/assets/m3_fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: lib/presentation/assets/m3_fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: lib/presentation/assets/m3_fonts/roboto/Roboto-Medium.ttf
          weight: 600
        - asset: lib/presentation/assets/m3_fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: lib/presentation/assets/m3_fonts/roboto/Roboto-Black.ttf
          weight: 800
    - family: Sail
      fonts:
        - asset: lib/presentation/assets/m3_fonts/sail/Sail-Regular.ttf
          weight: 400
    - family: Roboto Serif
      fonts:
        - asset: lib/presentation/assets/m3_fonts/roboto_serif/static/RobotoSerif-ExtraLight.ttf
          weight: 200
        - asset: lib/presentation/assets/m3_fonts/roboto_serif/static/RobotoSerif-Regular.ttf
          weight: 300
        - asset: lib/presentation/assets/m3_fonts/roboto_serif/static/RobotoSerif-Medium.ttf
          weight: 400
        - asset: lib/presentation/assets/m3_fonts/roboto_serif/static/RobotoSerif-SemiBold.ttf
          weight: 600
        - asset: lib/presentation/assets/m3_fonts/roboto_serif/static/RobotoSerif-Bold.ttf
          weight: 700
        - asset: lib/presentation/assets/m3_fonts/roboto_serif/static/RobotoSerif-ExtraBold.ttf
          weight: 800
        - asset: lib/presentation/assets/m3_fonts/roboto_serif/static/RobotoSerif-Black.ttf
          weight: 900



flutter_intl:
  enabled: true
  class_name: Translation
  main_locale: pl
  arb_dir: lib/presentation/utils/translation/l10n
  output_dir: lib/presentation/utils/translation/generated
