name: Dart and Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      flutter_version: 3.22.2
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Set up Flutter from fvm config
        id: setup
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          FLUTTER_VERSION=$(cat .fvm/fvm_config.json | jq -r '.flutterSdkVersion')
          echo "flutter_version=$FLUTTER_VERSION" >> $GITHUB_OUTPUT

  install_dependencies:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: 3.22.2
      - name: Clean Flutter project
        run: flutter clean
      - name: Install dependencies
        run: flutter pub get
      - name: Cache Flutter dependencies
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-
      - name: Validate Flutter installation
        run: flutter doctor -v

  run_build_runner_and_analyze:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: 3.22.2
      - name: Clean Flutter project
        run: flutter clean
      - name: Install dependencies
        run: flutter pub get
      - name: Run build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs --verbose
      - name: Analyze project source
        run: flutter analyze

  verify_formatting:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: 3.22.2
      - name: Verify formatting
        run: dart format lib test --line-length 120

  run_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: 3.22.2
      - name: Clean Flutter project
        run: flutter clean
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
